version: 0.2
phases:
  pre_build:
    commands:
      - terraform fmt
      # - terraform init
      # - terraform validate
  build:
    commands:
      - terraform apply --auto-approve
      - terraform destroy --auto-approve