version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
      - terraform fmt
  build:
    commands:
      - terraform apply --auto-approve
      - terraform destroy --auto-approve
  post_build:
    commands:
      - echo "Terraform desploy y destroy completado con exito!"