version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
      - ls -la
  build:
    commands:
      - terraform plan
  post_build:
    commands:
      - echo "Terraform plan ejecutado con exito!"